FROM node:18 as base

FROM base as dev
# Bundle app source
# WORKDIR /opt/app/expenses-manager

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
# COPY ../package*.json ./

# RUN npm install
# If you are building your code for production
# RUN npm ci --only=production
CMD [ "sleep", "infinity" ]